[package]
name = "semantics"
version.workspace = true
edition.workspace = true

[dependencies]
runtime-spec = { path = "../runtime-spec" }
ast = { path = "../ast" }
types = { path = "../types" }
symbols = { path = "../symbols" }
errors = { path = "../errors" }
tokens = { path = "../tokens" }
